Repository auth0/auth0-react, pull requests merged in 2020-10, with the labels that each got.

#129 Fix broken community link in the issue templates
  .github/ISSUE_TEMPLATE/config.yml
  FAQ.md
Labels: tiny

#147 [SDK-2104] Update peerDeps to account for react 17
  package.json
Labels: review:tiny

#150 [SDK-2106] Memoize auth methods
  __tests__/auth-provider.test.tsx
  src/auth0-provider.tsx
Labels: review:small
