Repository auth0/auth0-react, pull requests merged in 2020-08, with the labels that each got.

#84 Fix `npm run build` on Gatsby example
  examples/gatsby-app/src/components/Nav.js
Labels: tiny

#91 Update codecov and fix reports
  package-lock.json
  package.json
Labels: CH: Security, tiny

#92 Upgrade dependencies to latest
  package-lock.json
  package.json
Labels: CH: Security, tiny

#94 [SDK-1889] The Next.js and Gatsby tests are a little flakey
  cypress/integration/smoke.test.ts
Labels: tiny

#81 [SDK-1836] Update state for local logouts
  __tests__/auth-provider.test.tsx
  src/auth0-provider.tsx
  src/reducer.tsx
Labels: CH: Fixed, small

#95 Add issue templates
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/report-a-bug.md
  FAQ.md
  README.md
Labels: small
