Repository auth0/auth0-react, pull requests merged in 2020-06, with the labels that each got.

#32 Update README.md
  README.md
Labels: documentation, tiny

#33 Release 0.4.0
  .prettierignore
  CHANGELOG.md
  README.md
  docs/assets/css/main.css
  docs/assets/js/main.js
  docs/assets/js/search.json
  docs/classes/oautherror.html
  docs/globals.html
  docs/index.html
  docs/interfaces/advancedoptions.html
  docs/interfaces/auth0clientoptions.html
  docs/interfaces/auth0contextinterface.html
  docs/interfaces/auth0provideroptions.html
  docs/interfaces/getidtokenclaimsoptions.html
  docs/interfaces/gettokensilentlyoptions.html
  docs/interfaces/gettokenwithpopupoptions.html
  docs/interfaces/getuseroptions.html
  docs/interfaces/logoutoptions.html
  docs/interfaces/popupconfigoptions.html
  docs/interfaces/popuploginoptions.html
  docs/interfaces/redirectloginoptions.html
  docs/interfaces/redirectloginresult.html
  docs/interfaces/withauth0props.html
  package-lock.json
  package.json
  static/index.html
Labels: small

#34 Fix link to example in README.md
  README.md
Labels: tiny

#35 Add codecov and npm badges
  .circleci/config.yml
  README.md
  package-lock.json
  package.json
Labels: tiny

#36 Add a link to the quickstart
  README.md
Labels: tiny

#38 [SDK-1705] Next and Gatsby examples
  .circleci/config.yml
  EXAMPLES.md
  cypress.json
  cypress/integration/smoke.test.ts
  examples/README.md
  examples/cra-react-router/README.md
  examples/gatsby-app/.env.development.sample
  examples/gatsby-app/.eslintrc
  examples/gatsby-app/.gitignore
  examples/gatsby-app/.prettierignore
  examples/gatsby-app/.prettierrc
  examples/gatsby-app/README.md
  examples/gatsby-app/gatsby-browser.js
  examples/gatsby-app/gatsby-config.js
  examples/gatsby-app/package.json
  examples/gatsby-app/src/components/App.css
  examples/gatsby-app/src/components/Error.js
  examples/gatsby-app/src/components/Loading.js
  examples/gatsby-app/src/components/Nav.js
  examples/gatsby-app/src/components/ProtectedRoute.js
  examples/gatsby-app/src/components/Users.js
  examples/gatsby-app/src/hooks/use-api.js
  examples/gatsby-app/src/pages/index.js
  examples/nextjs-app/.env.sample
  examples/nextjs-app/.gitignore
  examples/nextjs-app/README.md
  examples/nextjs-app/components/App.css
  examples/nextjs-app/components/Error.js
  examples/nextjs-app/components/Loading.js
  examples/nextjs-app/components/Nav.js
  examples/nextjs-app/hooks/use-api.js
  examples/nextjs-app/package.json
  examples/nextjs-app/pages/_app.js
  examples/nextjs-app/pages/index.js
  examples/nextjs-app/pages/users.js
  examples/users-api/README.md
  package-lock.json
  package.json
Labels: medium

#39 [SDK-1704] Add contributing and troubleshooting guides
  CONTRIBUTING.md
  README.md
  TROUBLESHOOTING.md
  cypress/integration/smoke.test.ts
Labels: small

#41 Add extra options to withAuthenticationRequired
  README.md
  __tests__/with-authentication-required.test.tsx
  src/index.tsx
  src/with-authentication-required.tsx
  typedoc.js
Labels: CH: Breaking Change, medium

#42 Update examples to have `returnTo` option set in logout
  README.md
  examples/cra-react-router/src/Nav.tsx
  examples/gatsby-app/src/components/Nav.js
  examples/nextjs-app/components/Nav.js
  src/auth0-context.tsx
  static/index.html
Labels: small

#43 Fix some typos
  src/auth0-context.tsx
  src/auth0-provider.tsx
Labels: tiny

#45 Add some comments to the CRA example for hash routing
  examples/cra-react-router/src/App.tsx
  examples/cra-react-router/src/ProtectedRoute.tsx
  examples/cra-react-router/src/index.tsx
Labels: tiny

#48 Update QS link
  README.md
Labels: tiny
