Repository auth0/auth0-react, pull requests merged in 2021-04, with the labels that each got.

#227 [SDK-2456] Remove beta labelling for Organizations, with updated docs
  EXAMPLES.md
  docs/assets/js/search.js
  docs/classes/errors.oautherror.html
  docs/interfaces/auth0_context.auth0contextinterface.html
  docs/interfaces/auth0_context.redirectloginoptions.html
  docs/interfaces/auth0_provider.auth0provideroptions.html
  docs/interfaces/with_auth0.withauth0props.html
  docs/interfaces/with_authentication_required.withauthenticationrequiredoptions.html
  docs/modules/auth0_context.html
  docs/modules/auth0_provider.html
  docs/modules/use_auth0.html
  docs/modules/with_auth0.html
  docs/modules/with_authentication_required.html
  package-lock.json
  src/auth0-provider.tsx
Labels: documentation, tiny

#231 [SDK-2522] Check for state along with error param
  __tests__/auth-provider.test.tsx
  __tests__/utils.test.tsx
  examples/cra-react-router/src/Nav.tsx
  src/utils.tsx
Labels: review:small

#233 [SDK-2541] Expose handleRedirectCallback from auth0-spa-js
  __tests__/auth-provider.test.tsx
  src/auth0-context.tsx
  src/auth0-provider.tsx
  src/reducer.tsx
Labels: CH: Added, review:small
