Repository auth0/auth0-react, pull requests merged in 2021-09, with the labels that each got.

#270 Bump SPA JS to 1.17.1
  package-lock.json
  package.json
Labels: review:tiny

#271 [SDK-2731] Prepare for automated releasing
  .circleci/config.yml
  .shiprc
  package.json
Labels: review:small

#272 Release v1.7.0
  CHANGELOG.md
  docs/classes/errors.oautherror.html
  docs/classes/index.user.html
  docs/interfaces/auth0_context.auth0contextinterface.html
  docs/interfaces/auth0_context.redirectloginoptions.html
  docs/interfaces/auth0_provider.auth0provideroptions.html
  docs/interfaces/index.getidtokenclaimsoptions.html
  docs/interfaces/index.gettokensilentlyoptions.html
  docs/interfaces/index.icache.html
  docs/interfaces/index.logoutoptions.html
  docs/interfaces/index.logouturloptions.html
  docs/interfaces/index.popupconfigoptions.html
  docs/interfaces/with_auth0.withauth0props.html
  docs/interfaces/with_authentication_required.withauthenticationrequiredoptions.html
  docs/modules/auth0_context.html
  docs/modules/auth0_provider.html
  docs/modules/index.html
  docs/modules/use_auth0.html
  docs/modules/with_auth0.html
  docs/modules/with_authentication_required.html
  package-lock.json
  package.json
Labels: review:tiny

#279 Bump Auth0-SPA-JS to 1.18.0
  package-lock.json
  package.json
Labels: review:tiny

#281 Release v1.8.0
  CHANGELOG.md
  docs/classes/errors.oautherror.html
  docs/interfaces/auth0_context.auth0contextinterface.html
  docs/interfaces/auth0_context.redirectloginoptions.html
  docs/interfaces/auth0_provider.auth0provideroptions.html
  docs/interfaces/with_auth0.withauth0props.html
  docs/interfaces/with_authentication_required.withauthenticationrequiredoptions.html
  docs/modules/auth0_context.html
  docs/modules/auth0_provider.html
  docs/modules/use_auth0.html
  docs/modules/with_auth0.html
  docs/modules/with_authentication_required.html
  package-lock.json
  package.json
Labels: review:tiny

#283 Add connection property to Auth0ProviderOptions
  src/auth0-provider.tsx
Labels: CH: Fixed, review:tiny
