Repository auth0/auth0-react, pull requests merged in 2021-02, with the labels that each got.

#191 Update Types for LoginWithRedirect
  src/auth0-provider.tsx
Labels: CH: Changed, review:tiny

#192 [SDK-1838] Upgrade typedoc to 0.20.20
  docs/assets/css/main.css
  docs/assets/js/main.js
  docs/assets/js/search.js
  docs/assets/js/search.json
  docs/classes/errors.oautherror.html
  docs/classes/oautherror.html
  docs/globals.html
  docs/index.html
  docs/interfaces/advancedoptions.html
  docs/interfaces/auth0_context.auth0contextinterface.html
  docs/interfaces/auth0_context.redirectloginoptions.html
  docs/interfaces/auth0_provider.auth0provideroptions.html
  docs/interfaces/auth0clientoptions.html
  docs/interfaces/auth0contextinterface.html
  docs/interfaces/auth0provideroptions.html
  docs/interfaces/getidtokenclaimsoptions.html
  docs/interfaces/gettokensilentlyoptions.html
  docs/interfaces/gettokenwithpopupoptions.html
  docs/interfaces/getuseroptions.html
  docs/interfaces/index.getidtokenclaimsoptions.html
  docs/interfaces/index.gettokensilentlyoptions.html
  docs/interfaces/index.gettokenwithpopupoptions.html
  docs/interfaces/index.logoutoptions.html
  docs/interfaces/index.popupconfigoptions.html
  docs/interfaces/index.popuploginoptions.html
  docs/interfaces/logoutoptions.html
  docs/interfaces/logouturloptions.html
  docs/interfaces/popupconfigoptions.html
  docs/interfaces/popuploginoptions.html
  docs/interfaces/redirectloginoptions.html
  docs/interfaces/redirectloginresult.html
  docs/interfaces/with_auth0.withauth0props.html
  docs/interfaces/with_authentication_required.withauthenticationrequiredoptions.html
  docs/interfaces/withauth0props.html
  docs/interfaces/withauthenticationrequiredoptions.html
  docs/modules.html
  docs/modules/auth0_context.html
  docs/modules/auth0_provider.html
  docs/modules/errors.html
  docs/modules/index.html
  docs/modules/use_auth0.html
  docs/modules/with_auth0.html
  docs/modules/with_authentication_required.html
  package-lock.json
  package.json
  src/index.tsx
  typedoc.js
Labels: documentation

#194 Fix some dependabot alerts
  examples/users-api/package-lock.json
  examples/users-api/package.json
  jest.config.js
  package-lock.json
  package.json
Labels: review:small

#193 isLoading should default to true even when doing SSR
  __tests__/ssr.test.tsx
  src/auth-state.tsx
Labels: review:small

#190 feat: added buildAuthorizeUrl and buildLogoutUrl from auth0-spa-js
  __mocks__/@auth0/auth0-spa-js.tsx
  __tests__/auth-provider.test.tsx
  src/auth0-context.tsx
  src/auth0-provider.tsx
  src/index.tsx
Labels: review:small

#196 Fix buildAuthorizeUrl tests
  __tests__/auth-provider.test.tsx
Labels: review:tiny

#200 Release 1.3.0
  CHANGELOG.md
  docs/assets/js/search.js
  docs/classes/errors.oautherror.html
  docs/interfaces/auth0_context.auth0contextinterface.html
  docs/interfaces/auth0_context.redirectloginoptions.html
  docs/interfaces/auth0_provider.auth0provideroptions.html
  docs/interfaces/index.logouturloptions.html
  docs/interfaces/with_auth0.withauth0props.html
  docs/interfaces/with_authentication_required.withauthenticationrequiredoptions.html
  docs/modules/auth0_context.html
  docs/modules/auth0_provider.html
  docs/modules/index.html
  docs/modules/use_auth0.html
  docs/modules/with_auth0.html
  docs/modules/with_authentication_required.html
  package-lock.json
  package.json
Labels: review:small

#202 Update EXAMPLES.md
  EXAMPLES.md
Labels: review:tiny
